//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerInfoDataAccess
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ServerInfo
    {
        [Required]
        public int? server_id { get; set; }

        [Required]
        public string name { get; set; }

        [Required]
        public string loction { get; set; }

        [Required]
        public string date { get; set; }

        public override string ToString()
        {
            return string.Format("Server_id:{0},name:{1},location:{2},date:{3}",server_id,name,loction,date);
        }
    }
}
